name: duotask
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  themexpert: ^1.0.2
  cupertino_icons: ^1.0.6
  flutter_keyboard_visibility: ^6.0.0
  flutter_svg: ^2.0.10+1
  reorderables: ^0.6.0
  flutter_swipe_action_cell: ^3.1.3
  animated_list_plus: ^0.5.2

  # STATE
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  provider: ^6.1.2
  get_it: ^7.7.0

  # NAVIGATION
  auto_route: ^8.1.3

  # STORE
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  # UTILS
  rxdart: ^0.27.7
  equatable: ^2.0.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  collection: ^1.18.0
  diffutil_dart: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.10
  auto_route_generator: ^8.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/