/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Assets {
  static const String authCredJson = "assets/auth_cred_json.json";
  static const String calendar = "assets/icons/calendar.svg";
  static const String chat = "assets/icons/chat.svg";
  static const String check = "assets/icons/check.svg";
  static const String checkCircle = "assets/icons/check_circle.svg";
  static const String defaultResponseJson = "assets/default_response_json.json";
  static const String home = "assets/icons/home.svg";
  static const String tasksJson = "assets/tasks_json.json";
  static const String tokenJson = "assets/token_json.json";
  static const String trash = "assets/icons/trash.svg";
  static const String user = "assets/icons/user.svg";
}
