/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Assets {
  static const String add = "assets/icons/add.svg";
  static const String authCredJson = "assets/auth_cred_json.json";
  static const String calendar = "assets/icons/calendar.svg";
  static const String cancelCloseMultiplyCircle =
      "assets/icons/cancel_close_multiply_circle.svg";
  static const String chat = "assets/icons/chat.svg";
  static const String check = "assets/icons/check.svg";
  static const String checkCircle = "assets/icons/check_circle.svg";
  static const String checkCorrectMark = "assets/icons/check_correct_mark.svg";
  static const String close = "assets/icons/close.svg";
  static const String closeCircle = "assets/icons/close_circle.svg";
  static const String defaultResponseJson = "assets/default_response_json.json";
  static const String dragLines = "assets/icons/drag_lines.svg";
  static const String eyeViewRevealShow =
      "assets/icons/eye_view_reveal_show.svg";
  static const String eyeViewRevealShowClosed =
      "assets/icons/eye_view_reveal_show_closed.svg";
  static const String fbPng = "assets/icons/fb_png.png";
  static const String googlePng = "assets/icons/google_png.png";
  static const String home = "assets/icons/home.svg";
  static const String tasksJson = "assets/tasks_json.json";
  static const String tokenJson = "assets/token_json.json";
  static const String trash = "assets/icons/trash.svg";
  static const String user = "assets/icons/user.svg";
}
